version: '3.8'  # or use the version that fits your setup

services:
  mlflow:
    build:
      context: .
      dockerfile: mlflow.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "./mlflow_data:/home/mlflow_data"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge